# Generated by Django 3.0.4 on 2020-03-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Activity Title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='activity_img/', verbose_name='Activity Image')),
                ('content', models.CharField(blank=True, max_length=64, null=True, verbose_name='Activity Content')),
                ('rule', models.CharField(blank=True, max_length=64, null=True, verbose_name='Activity Rule')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Activity Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Activity End Time')),
                ('active', models.BooleanField(default=True, verbose_name='Activity Active')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Activitu Detail Name')),
                ('vote_count', models.IntegerField(default=0, verbose_name='Activitu Detail Vote Count')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='activity_detail_thumb/', verbose_name='Activity Detail Thumbnail')),
                ('file', models.FileField(blank=True, null=True, upload_to='activity_detail_file', verbose_name='Activity Detail File')),
                ('content', models.CharField(blank=True, max_length=64, null=True)),
                ('activity_type_id', models.CharField(choices=[('video', '影音类'), ('picture', '图片类'), ('document', '文档类')], max_length=64, verbose_name='Activity Page Type')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.Activity', verbose_name='Relation Activity')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='User Name')),
                ('password', models.CharField(max_length=64, verbose_name='PassWord')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=64, verbose_name='Activity Page Type')),
                ('IP', models.CharField(max_length=64, verbose_name='IP')),
                ('vote_time', models.DateTimeField(auto_now_add=True, verbose_name='Vote Record Create Time')),
                ('activity_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote_app.ActivityDetail')),
            ],
        ),
    ]
