# Generated by Django 3.0.4 on 2020-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Activity Content'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rule',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Activity Rule'),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Activity Detail Content'),
        ),
    ]
