# Generated by Django 3.0.4 on 2020-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_auto_20200314_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rule',
            field=models.TextField(blank=True, null=True, verbose_name='Activity Rule'),
        ),
    ]
